name: Deploy Book

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-unstable:
    name: Deploy

    runs-on: ubuntu-latest
    if: github.repository == 'zhaofengli/attic'

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: DeterminateSystems/nix-installer-action@v18

      - name: Cache Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock', 'Cargo.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          save: false

      - name: Build book
        run: nix build .#book -L

      - name: Copy book artifact
        run: |
          cp --recursive --dereference --no-preserve=mode,ownership result public

      - name: Upload book artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: public

      - name: Deploy book
        uses: actions/deploy-pages@v4.0.5
